### ISSUE TITLE
ecos solver setup null

### ISSUE THREAD

**Issue by abdxyz** [EmbersArc/SuccessiveConvexificationCpp#12] opened 2019-04-10 13:28 UTC
hi,I had already installed ksp and krpc.
but when I run the code,I met another problem.I cannot run the scpp program.
I debug the program ,find that ecos_setup receive a NULL return value.
Do you know what happed?
I'm interested to this project.If there are something I can do,I'd glad to help.

**Comment by abdxyz** [comment] 2019-04-10 13:29
![Screenshot from 2019-04-10 21-22-33](https://user-images.githubusercontent.com/33575653/55882773-a6708900-5bd7-11e9-88d8-c628bc4c04d5.png)

**Comment by EmbersArc** [comment] 2019-04-10 13:40
Yes that's a problem with the latest version of ECOS. Try version 2.0.6, that one works for me. It has to do with the fact that they internally switched from long int to int to store indices, but I don't have enough knowledge of C to figure out why that crashes the solver.
I mentioned it here: https://github.com/embotech/ecos/issues/167 and @echu is on it I think.

Contributions are always welcome. For now the necessary functionality is all there. Depending on your experience with C++ and your interests there are a couple of things that can be done or improved. For example the problem setup part is a bit tedious right now. It would be great if it was possible to just formulate the cost and constraints with Eigen matrices instead of having to loop over each value in the matrix (basically overload the <, = and > operators to take Eigen types). You can also implement your own models and problems, I'd be glad to help if you have an idea of what else to apply the algorithm to. And lastly of course it still doesn't quite work with KSP. It's pretty close and maybe you can figure out what's wrong with it.

**Comment by abdxyz** [comment] 2019-04-11 11:47
thanks a lot.I'm interested in run simulation in ksp,although I'm not familiar with ksp. :)
we can make ksp simulation more well,so that can show the work better.
then we can improve the setup part.

**Comment by abdxyz** [comment] 2019-04-11 11:53
i now can run scpp successfully.when i run scppksp,there are something wrong with the cppad.
this is my screenshot.
I load a craft.and launch it and they run the scppksp.

**Comment by abdxyz** [comment] 2019-04-11 11:54
![Screenshot from 2019-04-11 19-49-33](https://user-images.githubusercontent.com/33575653/55955275-91593000-5c93-11e9-80b6-255eed47bb06.png)

**Comment by EmbersArc** [comment] 2019-04-11 12:45
This can happen for various reasons. The issue is that krpc can't stream the value for one or more vessel members. In your case that might be because you have multiple engines. Only use one engine that is active and can be throttled. Build your rocket as simply as possible. Probe Core, Tanks and _one_ Engine.
Also make sure to start the solver only when you're already approaching the landing pad and the velocity vector roughly points in its direction.

**Comment by EmbersArc** [comment] 2019-10-02 15:23
original issue now fixed

**Closed as completed by EmbersArc** 2019-10-02 15:23 UTC
